# Generated by Django 4.1.6 on 2023-02-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("excelparser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariation", old_name="product_id", new_name="product",
        ),
    ]
